#!/usr/bin/env python3
"""ghidra_headless.py — Ghidra Headless 自动化反编译包装器

自动检测本地 Ghidra 安装，调用 analyzeHeadless 对二进制文件进行反编译分析。
未安装 Ghidra 时优雅降级，输出检测报告和安装指引。

Usage:
    python ghidra_headless.py check                  # 检测 Ghidra 安装状态
    python ghidra_headless.py import <binary>        # 将二进制导入 Ghidra 项目
    python ghidra_headless.py decompile <binary> <function_name>  # 反编译指定函数
    python ghidra_headless.py export-cfuncs <binary> # 批量导出所有函数伪代码
"""

from __future__ import annotations

import argparse
import glob as _glob
import json
import os
import re
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path


# ── Ghidra detection ────────────────────────────────────────────────────────────

def _find_ghidra_root() -> Path | None:
    """Auto-detect Ghidra installation directory."""
    env = os.environ.get("GHIDRA_HOME", "")
    if env:
        p = Path(env)
        if p.is_dir():
            return p

    # Exact paths
    candidates = [
        Path("C:/ghidra"),
        Path("C:/Program Files/ghidra"),
        Path("C:/Tools/ghidra"),
        Path.home() / "ghidra",
        Path("/opt/ghidra"),
        Path("/usr/local/ghidra"),
        Path("/Applications/ghidra"),
    ]
    for c in candidates:
        if c.is_dir():
            return c

    # Versioned directories (ghidra_11.3_PUBLIC, ghidra_10.4, etc.)
    parent_dirs = [
        Path("C:/"), Path("C:/Program Files"), Path("C:/Tools"),
        Path("/opt"), Path("/usr/local"),
    ]
    for parent in parent_dirs:
        if not parent.is_dir():
            continue
        matches = sorted(
            [Path(p) for p in _glob.glob(str(parent / "ghidra_*")) if Path(p).is_dir()],
            reverse=True,
        )
        if matches:
            return matches[0]

    return None


def _find_analyze_headless(ghidra_root: Path) -> Path | None:
    """Find the analyzeHeadless executable under a Ghidra install."""
    names = ["analyzeHeadless", "analyzeHeadless.bat", "analyzeHeadless.sh"]
    search_dirs = [
        ghidra_root / "support",
        ghidra_root,
    ]
    for d in search_dirs:
        for name in names:
            p = d / name
            if p.is_file():
                return p
    return None


def detect_ghidra() -> dict:
    """Check if Ghidra is installed and locate the headless analyzer."""
    root = _find_ghidra_root()
    result = {
        "installed": False,
        "root": str(root) if root else None,
        "analyzeHeadless": None,
        "java": shutil.which("java") is not None,
        "error": None,
    }
    if not root:
        result["error"] = "GHIDRA_HOME not set and no installation found in common paths"
        return result
    ah = _find_analyze_headless(root)
    if not ah:
        result["error"] = f"Ghidra root found at {root} but analyzeHeadless not located"
        return result
    if not result["java"]:
        result["error"] = "Java runtime not found (required by Ghidra)"
        return result
    result["installed"] = True
    result["analyzeHeadless"] = str(ah)
    return result


# ── Ghidra post-script generation ────────────────────────────────────────────────

GHIDRA_EXPORT_SCRIPT = """// Auto-generated by ghidra_headless.py
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.Program;
import ghidra.util.task.TaskMonitor;
import java.io.FileWriter;
import java.io.PrintWriter;

public class ExportFunctions extends GhidraScript {
    @Override
    public void run() throws Exception {
        Program program = getCurrentProgram();
        DecompInterface decomp = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        decomp.setOptions(opts);
        decomp.openProgram(program);

        String outPath = getScriptArgs()[0];
        PrintWriter pw = new PrintWriter(new FileWriter(outPath));
        FunctionIterator funcs = program.getFunctionManager().getFunctions(true);
        int count = 0;
        while (funcs.hasNext() && count < {max_funcs} && !monitor.isCancelled()) {
            Function func = funcs.next();
            if (func.isThunk() || func.isExternal()) continue;
            DecompileResults res = decomp.decompileFunction(func, 30, TaskMonitor.DUMMY);
            if (res != null && res.decompileCompleted()) {
                pw.println("// -------- " + func.getName() + " @ " + func.getEntryPoint() + " --------");
                pw.println(res.getDecompiledFunction().getC());
                pw.println();
                count++;
            }
        }
        pw.close();
        decomp.closeProgram();
        println("EXPORT_COUNT:" + count + " to " + outPath);
    }
}
"""

GHIDRA_DECOMPILE_ONE_SCRIPT = """// Auto-generated by ghidra_headless.py
import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.Program;
import ghidra.util.task.TaskMonitor;
import java.io.FileWriter;
import java.io.PrintWriter;

public class DecompileOne extends GhidraScript {
    @Override
    public void run() throws Exception {
        Program program = getCurrentProgram();
        String targetName = getScriptArgs()[0];
        String outPath = getScriptArgs()[1];
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(program);

        // Try address-based lookup first (faster, matches any format)
        boolean isAddr = targetName.startsWith("0x") || targetName.startsWith("0X")
                      || targetName.matches("[0-9a-fA-F]+");
        if (isAddr) {
            try {
                long targetAddr = Long.parseLong(
                    targetName.replaceFirst("^0[xX]", ""), 16);
                Function func = program.getFunctionManager().getFunctionAt(
                    program.getAddressFactory().getDefaultAddressSpace().getAddress(targetAddr));
                if (func != null && !func.isThunk() && !func.isExternal()) {
                    decompileAndWrite(decomp, func, outPath);
                    decomp.closeProgram();
                    return;
                }
            } catch (Exception e) {
                // Fall through to name-based search
            }
        }

        // Name-based search
        FunctionIterator funcs = program.getFunctionManager().getFunctions(true);
        while (funcs.hasNext() && !monitor.isCancelled()) {
            Function func = funcs.next();
            if (func.isThunk() || func.isExternal()) continue;
            if (func.getName().equals(targetName)) {
                decompileAndWrite(decomp, func, outPath);
                decomp.closeProgram();
                return;
            }
        }
        println("ERROR: function '" + targetName + "' not found");
        decomp.closeProgram();
    }

    private void decompileAndWrite(DecompInterface decomp, Function func, String outPath)
            throws Exception {
        DecompileResults res = decomp.decompileFunction(func, 30, TaskMonitor.DUMMY);
        if (res != null && res.decompileCompleted()) {
            PrintWriter pw = new PrintWriter(new FileWriter(outPath));
            pw.print(res.getDecompiledFunction().getC());
            pw.close();
            println("Decompiled " + func.getName() + " to " + outPath);
        } else {
            println("ERROR: decompilation failed for " + func.getName());
        }
    }
}
"""


def _write_ghidra_script(script_dir: Path, script_name: str, content: str,
                         max_funcs: int = 500) -> Path:
    """Write a Ghidra Java post-script to disk."""
    script_dir.mkdir(parents=True, exist_ok=True)
    filled = content.replace("{max_funcs}", str(max_funcs))
    out = script_dir / script_name
    out.write_text(filled, encoding="utf-8")
    return out


# ── Subprocess helpers ────────────────────────────────────────────────────────────

def _run_ghidra(analyze_headless: str, project_dir: str, project_name: str,
                binary: str, post_script: str | None = None,
                script_args: list[str] | None = None,
                import_only: bool = False, timeout: int = 600) -> subprocess.CompletedProcess:
    """Run analyzeHeadless safely (no shell)."""
    cmd = [analyze_headless, project_dir, project_name]
    if import_only:
        cmd += ["-import", binary]
    else:
        cmd += ["-process", binary]
        if post_script:
            cmd += ["-postScript", post_script]
            if script_args:
                cmd.extend(script_args)
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)


def _safe_name(file_path: str) -> str:
    """Derive a safe project/binary name from a file path."""
    name = Path(file_path).stem
    name = re.sub(r'[^\w\-]', '_', name)
    return name[:50]


def _check_binary(path: str) -> Path | None:
    """Validate and resolve a binary path. Returns None if not a regular file."""
    p = Path(path).resolve()
    if not p.is_file():
        return None
    return p


# ── Command: import ─────────────────────────────────────────────────────────────

def cmd_import(ghidra: dict, binary: str, project_dir: str | None = None,
               project_name: str | None = None) -> dict:
    """Import a binary into a Ghidra project (non-shared)."""
    if not ghidra["installed"]:
        return {"error": "Ghidra not installed"}

    bin_path = _check_binary(binary)
    if not bin_path:
        return {"error": f"Not a regular file: {binary}"}

    proj_dir = project_dir or str(Path(tempfile.gettempdir()) / "ghidra_projects")
    proj_name = project_name or _safe_name(binary)
    Path(proj_dir).mkdir(parents=True, exist_ok=True)

    result = {
        "action": "import",
        "binary": str(bin_path),
        "project_dir": proj_dir,
        "project_name": proj_name,
        "success": False,
    }
    try:
        proc = _run_ghidra(ghidra["analyzeHeadless"], proj_dir, proj_name,
                           str(bin_path), import_only=True)
        result["returncode"] = proc.returncode
        result["stderr"] = proc.stderr[:2000] if proc.stderr else ""
        result["stdout"] = proc.stdout[:2000] if proc.stdout else ""
        result["success"] = proc.returncode == 0
        if proc.returncode != 0:
            result["error"] = proc.stderr[:500] or "analyzeHeadless returned non-zero"
    except subprocess.TimeoutExpired:
        result["error"] = "Import timed out (10 min limit)"
    except OSError as e:
        result["error"] = f"Failed to launch analyzeHeadless: {e}"
    return result


# ── Command: decompile ───────────────────────────────────────────────────────────

def cmd_decompile(ghidra: dict, binary: str, func_name: str,
                  project_dir: str | None = None,
                  project_name: str | None = None) -> dict:
    """Decompile a single function by name or address."""
    if not ghidra["installed"]:
        return {"error": "Ghidra not installed"}

    bin_path = _check_binary(binary)
    if not bin_path:
        return {"error": f"Not a regular file: {binary}"}

    proj_dir = project_dir or str(Path(tempfile.gettempdir()) / "ghidra_projects")
    proj_name = project_name or _safe_name(binary)
    Path(proj_dir).mkdir(parents=True, exist_ok=True)

    script_dir = Path(proj_dir) / "ghidra_scripts"
    script_path = _write_ghidra_script(script_dir, "DecompileOne.java",
                                        GHIDRA_DECOMPILE_ONE_SCRIPT)

    out_dir = Path(proj_dir) / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{_safe_name(func_name)}.c"

    result = {
        "action": "decompile",
        "binary": str(bin_path),
        "function": func_name,
        "output_file": str(out_file),
        "success": False,
    }
    try:
        proc = _run_ghidra(ghidra["analyzeHeadless"], proj_dir, proj_name,
                           str(bin_path), post_script=str(script_path),
                           script_args=[func_name, str(out_file)])
        result["returncode"] = proc.returncode
        result["stderr"] = proc.stderr[:2000] if proc.stderr else ""
        result["success"] = proc.returncode == 0 and out_file.is_file()
        if result["success"]:
            result["decompiled_code"] = out_file.read_text(encoding="utf-8", errors="replace")
        else:
            result["error"] = proc.stderr[:500] or "Decompilation failed"
    except subprocess.TimeoutExpired:
        result["error"] = "Decompilation timed out (10 min limit)"
    except OSError as e:
        result["error"] = f"Failed to launch analyzeHeadless: {e}"
    return result


# ── Command: export-cfuncs ────────────────────────────────────────────────────────

def cmd_export_cfuncs(ghidra: dict, binary: str, project_dir: str | None = None,
                       project_name: str | None = None, max_funcs: int = 500) -> dict:
    """Export decompiled C pseudocode for all non-thunk, non-external functions."""
    if not ghidra["installed"]:
        return {"error": "Ghidra not installed"}

    bin_path = _check_binary(binary)
    if not bin_path:
        return {"error": f"Not a regular file: {binary}"}

    proj_dir = project_dir or str(Path(tempfile.gettempdir()) / "ghidra_projects")
    proj_name = project_name or _safe_name(binary)
    Path(proj_dir).mkdir(parents=True, exist_ok=True)

    script_dir = Path(proj_dir) / "ghidra_scripts"
    script_path = _write_ghidra_script(script_dir, "ExportFunctions.java",
                                        GHIDRA_EXPORT_SCRIPT, max_funcs)

    out_dir = Path(proj_dir) / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{_safe_name(binary)}_cfuncs.txt"

    result = {
        "action": "export_cfuncs",
        "binary": str(bin_path),
        "output_file": str(out_file),
        "max_funcs": max_funcs,
        "success": False,
    }
    try:
        proc = _run_ghidra(ghidra["analyzeHeadless"], proj_dir, proj_name,
                           str(bin_path), post_script=str(script_path),
                           script_args=[str(out_file)])
        result["returncode"] = proc.returncode
        result["stderr"] = proc.stderr[:2000] if proc.stderr else ""
        result["success"] = proc.returncode == 0 and out_file.is_file()
        if result["success"]:
            code = out_file.read_text(encoding="utf-8", errors="replace")
            # Extract count from Java output: EXPORT_COUNT:123 to ...
            m = re.search(r"EXPORT_COUNT:(\d+)", proc.stdout or "")
            result["function_count"] = int(m.group(1)) if m else 0
            result["output_size_bytes"] = len(code)
        else:
            result["error"] = proc.stderr[:500] or "Export failed"
    except subprocess.TimeoutExpired:
        result["error"] = "Export timed out (10 min limit)"
    except OSError as e:
        result["error"] = f"Failed to launch analyzeHeadless: {e}"
    return result


# ── Report generation ─────────────────────────────────────────────────────────────

def generate_markdown(data: dict) -> str:
    """Convert detection or decompile results into Markdown."""
    if data.get("action") == "check":
        lines = [
            "# Ghidra Headless Detection Report",
            f"- Generated UTC: {datetime.now(timezone.utc).isoformat()}",
            f"- Installed: {'yes' if data.get('installed') else 'no'}",
            f"- Ghidra root: {data.get('root') or 'N/A'}",
            f"- analyzeHeadless: {data.get('analyzeHeadless') or 'N/A'}",
            f"- Java available: {'yes' if data.get('java') else 'no'}",
        ]
        if data.get("error"):
            lines.append(f"- Error: {data['error']}")
        lines += ["", "## Install Ghidra",
                  "1. Download from https://github.com/NationalSecurityAgency/ghidra/releases",
                  "2. Extract and set GHIDRA_HOME environment variable",
                  "3. Ensure Java 17+ is installed (java --version)",
                  "4. Re-run: python ghidra_headless.py check",
                  ""]
        return "\n".join(lines)

    if data.get("action") == "import":
        lines = [
            "# Ghidra Import Result",
            f"- Generated UTC: {datetime.now(timezone.utc).isoformat()}",
            f"- Binary: {data.get('binary')}",
            f"- Project: {data.get('project_dir')}/{data.get('project_name')}",
            f"- Success: {data.get('success')}",
        ]
        if data.get("error"):
            lines += ["", f"Error: {data['error']}", ""]
        return "\n".join(lines)

    if data.get("action") == "decompile":
        lines = [
            "# Ghidra Decompile Result",
            f"- Generated UTC: {datetime.now(timezone.utc).isoformat()}",
            f"- Binary: {data.get('binary')}",
            f"- Function: {data.get('function')}",
            f"- Success: {data.get('success')}",
        ]
        if data.get("decompiled_code"):
            lines += ["", "```c", data["decompiled_code"], "```", ""]
        if data.get("error"):
            lines += ["", f"Error: {data['error']}", ""]
        return "\n".join(lines)

    if data.get("action") == "export_cfuncs":
        lines = [
            "# Ghidra Batch Export Result",
            f"- Generated UTC: {datetime.now(timezone.utc).isoformat()}",
            f"- Binary: {data.get('binary')}",
            f"- Functions exported: {data.get('function_count', 0)}",
            f"- Output file: {data.get('output_file', 'N/A')}",
            f"- Output size: {data.get('output_size_bytes', 0)} bytes",
            f"- Success: {data.get('success')}",
        ]
        if data.get("error"):
            lines += ["", f"Error: {data['error']}", ""]
        return "\n".join(lines)

    return json.dumps(data, indent=2, ensure_ascii=False)


# ── Argparse helpers ──────────────────────────────────────────────────────────────

def _shared_args():
    """Return a parent parser with shared --json/--out flags."""
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument("--out", help="Output path (.json or .md)")
    p.add_argument("--json", action="store_true", help="Output JSON (default: Markdown)")
    return p


# ── Main ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ghidra Headless 自动化反编译包装器",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Examples:
  python ghidra_headless.py check
  python ghidra_headless.py import ./target.exe
  python ghidra_headless.py decompile ./target.exe main
  python ghidra_headless.py decompile ./target.exe 0x401000
  python ghidra_headless.py export-cfuncs ./target.exe --max-funcs 200""",
    )
    sub = parser.add_subparsers(dest="command", help="Subcommand")
    shared = _shared_args()

    sub.add_parser("check", parents=[shared],
                   help="Detect Ghidra installation status")

    p_import = sub.add_parser("import", parents=[shared],
                              help="Import binary into Ghidra project")
    p_import.add_argument("binary", help="Path to target binary")
    p_import.add_argument("--project-dir", help="Ghidra project directory")
    p_import.add_argument("--project-name", help="Ghidra project name")

    p_dec = sub.add_parser("decompile", parents=[shared],
                           help="Decompile a single function")
    p_dec.add_argument("binary", help="Path to target binary")
    p_dec.add_argument("function", help="Function name or address (e.g. main or 0x401000)")
    p_dec.add_argument("--project-dir", help="Ghidra project directory")
    p_dec.add_argument("--project-name", help="Ghidra project name")

    p_exp = sub.add_parser("export-cfuncs", parents=[shared],
                           help="Batch export all functions as C pseudocode")
    p_exp.add_argument("binary", help="Path to target binary")
    p_exp.add_argument("--project-dir", help="Ghidra project directory")
    p_exp.add_argument("--project-name", help="Ghidra project name")
    p_exp.add_argument("--max-funcs", type=int, default=500, metavar="N",
                       choices=range(1, 100001),
                       help="Max functions to export (1-100000, default: 500)")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        return 1

    # ── check ──
    if args.command == "check":
        result = detect_ghidra()
        result["action"] = "check"
        rendered = json.dumps(result, indent=2, ensure_ascii=False) if args.json else generate_markdown(result)
        if args.out:
            Path(args.out).write_text(rendered, encoding="utf-8")
            print(args.out)
        else:
            print(rendered)
        return 0 if result["installed"] else 1

    # ── all other commands require Ghidra ──
    ghidra = detect_ghidra()
    if not ghidra["installed"]:
        ghidra["action"] = "check"
        rendered = json.dumps(ghidra, indent=2, ensure_ascii=False) if args.json else generate_markdown(ghidra)
        if args.out:
            Path(args.out).write_text(rendered, encoding="utf-8")
            print(args.out)
        else:
            print(rendered)
        return 1

    if args.command == "import":
        result = cmd_import(ghidra, args.binary, args.project_dir, args.project_name)
    elif args.command == "decompile":
        result = cmd_decompile(ghidra, args.binary, args.function, args.project_dir, args.project_name)
    elif args.command == "export-cfuncs":
        result = cmd_export_cfuncs(ghidra, args.binary, args.project_dir, args.project_name, args.max_funcs)
    else:
        parser.print_help()
        return 1

    rendered = json.dumps(result, indent=2, ensure_ascii=False) if args.json else generate_markdown(result)
    if args.out:
        Path(args.out).write_text(rendered, encoding="utf-8")
        print(args.out)
    else:
        print(rendered)
    return 0 if result.get("success") or result.get("installed") else 1


if __name__ == "__main__":
    raise SystemExit(main())
